version: "3.8"
services:
  reverseproxy:
    build:
      context: ./udagram-reverse-proxy
    image: linda96/udagram-reverse-proxy
  backend_user:
    build:
      context: ./udagram-api-users
    image: linda96/udagram-api-users
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: linda96/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend  
    image: linda96/udagram-frontend